# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Qlesson
                                 A QGIS plugin
 This plugin help promotes learning of Geographic Information Systems (GIS) and Remote Sensing concepts in a guided semi-interactive manner within the Qgis environment.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-07-07
        copyright            : (C) 2023 by Pascal Ogola
        email                : passies95@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

from .lessonregistry import QLessonRegistry
lessonsRegistry = QLessonRegistry()

# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Qlesson class from file Qlesson.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .qlesson import Qlesson
    return Qlesson(iface)
